<?php
require __DIR__ . '/../admin/includes/db.php';
$pdo = get_db();

// 1. Add default_meal_time column if missing
$cols = $pdo->query("SHOW COLUMNS FROM `food_menu`")->fetchAll(PDO::FETCH_COLUMN);
if (!in_array('default_meal_time', $cols)) {
    $pdo->exec("ALTER TABLE `food_menu` ADD COLUMN `default_meal_time` VARCHAR(50) DEFAULT 'breakfast' AFTER `category`");
    echo "Added default_meal_time column.\n";
}

// 2. Clear old demo items and insert genuine menu card items
$pdo->exec("DELETE FROM `food_menu`");

$menu_items = [
    // --- BREAKFAST ---
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Thattu Dosa (Set – 3 Nos)',
        'subtitle' => 'Traditional small spongy dosas served with stone-ground chutney and sambar',
        'price' => 75.00,
        'price_note' => 'Set of 3',
        'dietary_type' => 'veg',
        'badge' => 'ESTATE TIFFIN',
        'description' => 'Tender, spongy thattu dosas roasted on hot tawa with farm ghee or oil, served with fresh coconut chutney and piping hot sambar.',
        'inclusions' => "3 Spongy Thattu Dosas\nFresh Coconut Chutney\nEarthen Pot Sambar",
        'image_url' => 'assets/images/food_dosa_set.jpg',
        'display_order' => 1
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Masala Dosa',
        'subtitle' => 'Crisp golden crepe filled with gently spiced tempered potato masala',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'POPULAR',
        'description' => 'Crispy golden roasted dosa lined with aromatic spices, wrapped around savory potato masala with mustard and curry leaves.',
        'inclusions' => "1 Crisp Masala Dosa\nPotato Masala Filling\nCoconut & Tomato Chutneys\nHot Vegetable Sambar",
        'image_url' => 'assets/images/food_dosa_set.jpg',
        'display_order' => 2
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Egg Dosa',
        'subtitle' => 'Crisp dosa topped with farm-fresh beaten egg, crushed pepper and shallots',
        'price' => 75.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'non-veg',
        'badge' => 'FARM EGG',
        'description' => 'Hot roasted dosa enriched with a freshly beaten country egg, spiced with freshly ground mountain black pepper and green chilies.',
        'inclusions' => "1 Egg Enriched Dosa\nCoconut Chutney\nPiping Sambar",
        'image_url' => 'assets/images/food_dosa_set.jpg',
        'display_order' => 3
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Idli (Set – 3 Nos)',
        'subtitle' => 'Pillowy steamed fermented rice and black lentil cakes',
        'price' => 75.00,
        'price_note' => 'Set of 3',
        'dietary_type' => 'veg',
        'badge' => 'LIGHT & HEALTHY',
        'description' => 'Soft, melt-in-the-mouth steamed idlis made from naturally fermented native grain batter, paired with stone-ground coconut chutney.',
        'inclusions' => "3 Steamed Soft Idlis\nCoconut Chutney\nVegetable Sambar",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Idiyappam',
        'subtitle' => 'Delicate steamed string hoppers made of roasted rice flour',
        'price' => 20.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'CLASSIC',
        'description' => 'Silky soft steamed rice vermicelli nests, wonderful with vegetable stew or spicy kadala curry.',
        'inclusions' => "Steamed Rice Idiyappam\nFreshly Prepared",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 5
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Puttu',
        'subtitle' => 'Steamed cylinders of coarsely ground rice layered with fresh coconut',
        'price' => 30.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'KERALA SPECIAL',
        'description' => 'Traditional aromatic steamed puttu layered with freshly grated sweet coconut from the sanctuary estate.',
        'inclusions' => "Steamed Bamboo Puttu\nFresh Grated Coconut",
        'image_url' => 'assets/images/01 (1).jpeg',
        'display_order' => 6
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Kerala Kadala Curry',
        'subtitle' => 'Black chickpeas simmered in a roasted coconut & mountain spices gravy',
        'price' => 60.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'BESTSELLER',
        'description' => 'The ultimate accompaniment for Puttu and Idiyappam, slow-cooked with roasted coconut, shallots, and fragrant curry leaves.',
        'inclusions' => "Slow-Braised Black Chickpeas\nRoasted Coconut Gravy",
        'image_url' => 'assets/images/01 (1).jpeg',
        'display_order' => 7
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Veg Stew',
        'subtitle' => 'Mildly spiced seasonal farm vegetables simmered in rich coconut milk',
        'price' => 100.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'MILD & CREAMY',
        'description' => 'Heirloom potatoes, carrots, and sweet green peas simmered in fresh pressed coconut milk infused with whole spices and ginger.',
        'inclusions' => "Farm Vegetables in Coconut Milk Stew\nAromatic Whole Spices",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 8
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Egg Curry',
        'subtitle' => 'Boiled eggs simmered in a spicy shallot, tomato, and coconut gravy',
        'price' => 60.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'non-veg',
        'badge' => 'HOMESTYLE',
        'description' => 'Fresh boiled eggs with shallow slits, slow-cooked in a robust roasted onion-tomato gravy with native Kerala spices.',
        'inclusions' => "Boiled Farm Eggs\nRich Spiced Kerala Gravy",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 9
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Pongal',
        'subtitle' => 'Hearty comfort dish of rice and yellow moong lentils tempered with ghee, cumin & cashew',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'WARM COMFORT',
        'description' => 'Creamy, rich hot ven pongal glistening with pure farm ghee, whole black pepper, crushed ginger, and golden fried cashew nuts.',
        'inclusions' => "Ghee Ven Pongal\nCoconut Chutney\nHot Sambar",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 10
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Peas Curry',
        'subtitle' => 'Green peas cooked in creamy spiced coconut milk gravy',
        'price' => 100.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'GARDEN FRESH',
        'description' => 'Tender high-altitude green peas slow-simmered in a mildly spiced onion, tomato, and coconut milk gravy.',
        'inclusions' => "Tender Green Peas Gravy",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 11
    ],
    [
        'category' => 'breakfast',
        'default_meal_time' => 'breakfast',
        'heading' => 'Mixed Veg Curry',
        'subtitle' => 'Assortment of fresh garden vegetables cooked in fragrant local spices',
        'price' => 140.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'FARM HARVEST',
        'description' => 'Freshly picked farm vegetables stewed in rich, savory spiced curry with curry leaves and mustard seeds.',
        'inclusions' => "Mixed Farm Veggies\nFragrant Spiced Curry",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 12
    ],

    // --- LUNCH ---
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Kerala Rice (Ponni)',
        'subtitle' => 'Steamed superior quality Ponni rice',
        'price' => 60.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'STAPLE GRAIN',
        'description' => 'Fragrant, soft steamed Ponni rice cooked to perfection.',
        'inclusions' => "Fresh Steamed Ponni Rice",
        'image_url' => 'assets/images/food_kerala_sadya.jpg',
        'display_order' => 1
    ],
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Veg Meals',
        'subtitle' => 'Complete traditional Kerala meals with rice, sambar, rasam, kootu, thoran, curd & pickle',
        'price' => 120.00,
        'price_note' => 'Per Meal',
        'dietary_type' => 'veg',
        'badge' => 'FULL SADYA MEAL',
        'description' => 'Wholesome harvest lunch on plantain leaf with steamed rice, seasonal thoran, avial, drumstick sambar, rasam, moru, papadam, and pickle.',
        'inclusions' => "Steamed Rice\nDrumstick Sambar\nSpicy Rasam\nSeasonal Vegetable Thoran\nAvial\nPapadam & Pickle\nFarm Buttermilk",
        'image_url' => 'assets/images/food_kerala_sadya.jpg',
        'display_order' => 2
    ],
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Fried Rice',
        'subtitle' => 'Wok-tossed basmati rice with finely diced crisp farm vegetables',
        'price' => 150.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'POPULAR',
        'description' => 'Fragrant long-grain basmati rice tossed on high flame with farm carrots, cabbage, spring onion, and crushed pepper.',
        'inclusions' => "Vegetable Fried Rice\nChili Sauce & Tomato Dip",
        'image_url' => 'assets/images/01 (13).jpeg',
        'display_order' => 3
    ],
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Curd Rice',
        'subtitle' => 'Creamy tempered yogurt rice with mustard seeds, curry leaves & pomegranate',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'COOLING & REFRESHING',
        'description' => 'Cooling comforting rice mixed with fresh farm curd, tempered with mustard seeds, ginger, green chilies, and curry leaves.',
        'inclusions' => "Tempered Curd Rice\nCrisp Papadam\nHomemade Pickle",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Lemon Rice',
        'subtitle' => 'Tangy rice tempered with fresh farm lime juice, roasted peanuts and spices',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'ZESTY CITRUS',
        'description' => 'Bright, aromatic rice seasoned with fresh lemon juice, turmeric, crunchy roasted peanuts, and mild green chilies.',
        'inclusions' => "Tangy Spiced Lemon Rice\nRoasted Peanuts\nPickle",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 5
    ],
    [
        'category' => 'lunch',
        'default_meal_time' => 'lunch',
        'heading' => 'Chicken Biriyani',
        'subtitle' => 'Fragrant Malabar dum biriyani layered with tender chicken pieces & caramelized onions',
        'price' => 220.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'non-veg',
        'badge' => 'SPECIALTY DUM',
        'description' => 'Slow-cooked aromatic biriyani made with aged rice, tender country chicken marinated in rich masala, topped with fried cashews, raisins, and mint.',
        'inclusions' => "Aromatic Chicken Biriyani\nRefreshing Onion Raitha\nLemon Pickle\nPapadam",
        'image_url' => 'assets/images/01 (13).jpeg',
        'display_order' => 6
    ],

    // --- EVENING SPECIAL (TEAS & COFFEE) & SNACKS ---
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Tea',
        'subtitle' => 'Freshly brewed mountain tea with farm fresh milk',
        'price' => 20.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'ESTATE TEA',
        'description' => 'Hot aromatic black tea brewed with crushed tea leaves and pure fresh milk.',
        'inclusions' => "Piping Hot Kerala Chai",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 1
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Masala Tea',
        'subtitle' => 'Steaming milk tea infused with cardamom, cloves, and cinnamon',
        'price' => 30.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'SPICED CHAI',
        'description' => 'Freshly pounded cardamom, cinnamon, and cloves infused into simmering milk tea.',
        'inclusions' => "High-Range Spiced Tea",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 2
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Ginger Tea',
        'subtitle' => 'Energizing tea infused with crushed fresh mountain ginger',
        'price' => 30.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'FRESH GINGER',
        'description' => 'Warm, soothing tea prepared with hand-crushed spicy farm ginger and jaggery or sugar.',
        'inclusions' => "Fresh Ginger Infused Tea",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 3
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Lemon Tea',
        'subtitle' => 'Refreshing black tea with fresh lime squeeze and mint',
        'price' => 30.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'REFRESHING',
        'description' => 'Light, uplifting freshly brewed tea infused with sun-ripened farm lemons.',
        'inclusions' => "Fresh Lemon Tea",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 4
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Organic Green Tea',
        'subtitle' => 'Pure unfermented whole leaf organic green tea rich in antioxidants',
        'price' => 30.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => '100% ORGANIC',
        'description' => 'Gentle, cleansing high-altitude green tea brewed from single-estate leaves.',
        'inclusions' => "Organic Green Tea Infusion",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 5
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Coffee',
        'subtitle' => 'South Indian style decoction coffee brewed with foamy milk',
        'price' => 30.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'FILTER COFFEE',
        'description' => 'Rich, fragrant roasted coffee bean decoction pulled with frothy hot farm milk.',
        'inclusions' => "Hot Frothy South Indian Coffee",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 6
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Bru Coffee',
        'subtitle' => 'Smooth and rich instant Bru coffee',
        'price' => 40.00,
        'price_note' => 'Per Cup',
        'dietary_type' => 'veg',
        'badge' => 'INSTANT BRU',
        'description' => 'Creamy Bru coffee served piping hot.',
        'inclusions' => "Hot Creamy Bru Coffee",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 7
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Banana Fry',
        'subtitle' => 'Crisp golden fritters made with sweet ripe Kerala Nendran bananas (Pazham Pori)',
        'price' => 20.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'PAZHAM PORI',
        'description' => 'Sweet ripe plantains dipped in light batter and deep-fried to a golden crunch. The ultimate tea-time companion.',
        'inclusions' => "Golden Nendran Banana Fritters",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 8
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Ulli Vada',
        'subtitle' => 'Crispy spiced sliced onion patties deep fried with curry leaves and green chilies',
        'price' => 20.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'CRISPY BITE',
        'description' => 'Crispy, crunchy Kerala tea-shop style onion fritters packed with sliced onions, ginger, and curry leaves.',
        'inclusions' => "Crunchy Spiced Onion Vada",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 9
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Onion Pakkavada',
        'subtitle' => 'Crunchy ribbon pakkavada ribbons seasoned with red chili and asafoetida',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'SHARING PLATE',
        'description' => 'Traditional crisp pakkavada strips deep fried with roasted garlic, onions, and curry leaves.',
        'inclusions' => "Generous Plate of Crunchy Pakkavada",
        'image_url' => 'assets/images/food_evening_snacks.jpg',
        'display_order' => 10
    ],
    [
        'category' => 'snacks',
        'default_meal_time' => 'snacks',
        'heading' => 'Finger Chips',
        'subtitle' => 'Golden fried French fries seasoned with fine salt and herbs',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'KIDS FAVORITE',
        'description' => 'Crisp potato finger chips fried to a golden hue, served with tomato ketchup.',
        'inclusions' => "Plate of Hot Finger Chips\nTomato Ketchup",
        'image_url' => 'assets/images/01 (19).jpeg',
        'display_order' => 11
    ],

    // --- HEALTHY JUICES ---
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Sugarcane with Flavours',
        'subtitle' => 'Fresh cold-pressed sugarcane juice infused with your favorite natural flavour',
        'price' => 120.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'ESTATE JUICE',
        'description' => '100% natural pure sugarcane juice. Available Flavours: Strawberry, Passion Fruit, Banana, Pineapple, Watermelon, Rose Petals.',
        'inclusions' => "Cold Pressed Sugarcane Juice\nChoice of Natural Flavour",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 1
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Sugarcane Juice (Pure)',
        'subtitle' => 'Pure unadulterated cold-pressed sugarcane with a hint of ginger and lime',
        'price' => 60.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'PURE CANE',
        'description' => 'Freshly crushed natural cane stalks from nearby fields with a drop of fresh lime.',
        'inclusions' => "Pure Sugarcane Juice with Lime & Ginger",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 2
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Passion Fruit Juice',
        'subtitle' => 'Exotic tart & sweet nectar made with mountain-grown passion fruit',
        'price' => 100.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'FARM FRESH',
        'description' => 'Freshly harvested Kanthalloor passion fruit pulp blended chilled with wild mountain honey or raw sugar.',
        'inclusions' => "Chilled Passion Fruit Nectar",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 3
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Strawberry Juice',
        'subtitle' => 'Freshly picked Kanthalloor red strawberries blended chilled',
        'price' => 100.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'ORCHARD SPECIAL',
        'description' => 'Juicy sweet strawberries handpicked from Kanthalloor cold-climate orchards.',
        'inclusions' => "Fresh Strawberry Juice",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Pineapple Juice',
        'subtitle' => 'Sweet and tangy fresh pineapple juice',
        'price' => 80.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'VITAMIN C',
        'description' => 'Sun-ripened pineapple blended fresh with a pinch of rock salt.',
        'inclusions' => "Chilled Fresh Pineapple Juice",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 5
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Guava Juice',
        'subtitle' => 'Aromatic pink farm guava blended smooth with light spices',
        'price' => 100.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'PINK GUAVA',
        'description' => 'Rich in fiber and vitamin C, made with ripe garden guavas.',
        'inclusions' => "Smooth Pink Guava Juice",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 6
    ],
    [
        'category' => 'juices',
        'default_meal_time' => 'snacks',
        'heading' => 'Watermelon Juice',
        'subtitle' => 'Chilled thirst-quenching pure watermelon juice',
        'price' => 60.00,
        'price_note' => 'Per Glass',
        'dietary_type' => 'veg',
        'badge' => 'HYDRATING',
        'description' => 'Sweet ruby watermelon pressed fresh without added water.',
        'inclusions' => "Pure Chilled Watermelon Juice",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 7
    ],

    // --- MILLET SPECIALS ---
    [
        'category' => 'millet',
        'default_meal_time' => 'breakfast',
        'heading' => 'Millet Dosa',
        'subtitle' => 'Nutritious crisp dosa made with ancient barnyard & finger millets',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'ANCIENT GRAIN',
        'description' => 'Rich in dietary fiber and minerals, roasted crisp with cold-pressed gingelly oil.',
        'inclusions' => "Crisp Millet Dosa\nCoconut Chutney\nSambar",
        'image_url' => 'assets/images/food_dosa_set.jpg',
        'display_order' => 1
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'breakfast',
        'heading' => 'Millet Idli',
        'subtitle' => 'Steamed spongy cakes made from nutrient-packed sprouted millets',
        'price' => 70.00,
        'price_note' => 'Set of 3',
        'dietary_type' => 'veg',
        'badge' => 'LOW GI & HEALTHY',
        'description' => 'Light, easily digestible steamed idlis made with foxtail and little millet batter.',
        'inclusions' => "3 Steamed Millet Idlis\nChutney & Sambar",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 2
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'breakfast',
        'heading' => 'Millet Idiyappam',
        'subtitle' => 'Soft steamed string hoppers extruded from ragi & foxtail millet flour',
        'price' => 40.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'FIBER RICH',
        'description' => 'Earthy, delicious steamed string hoppers, great with curry or coconut milk.',
        'inclusions' => "Steamed Millet Idiyappam",
        'image_url' => 'assets/images/01 (10).jpeg',
        'display_order' => 3
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'lunch',
        'heading' => 'Millet Biriyani',
        'subtitle' => 'Slow-cooked aromatic biriyani made with whole kodo millets and garden vegetables',
        'price' => 250.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'NUTRI DUM',
        'description' => 'Gourmet health twist on classic biriyani using aged millets layered with garden veggies, mint, and saffron.',
        'inclusions' => "Flavorsome Millet Dum Biriyani\nRaitha & Spiced Gravy",
        'image_url' => 'assets/images/01 (13).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'lunch',
        'heading' => 'Millet Pulav with Cut Vegetables',
        'subtitle' => 'Delicately spiced millet pilaf cooked with garden beans, carrots & sweet peas',
        'price' => 180.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'HEART HEALTHY',
        'description' => 'Fluffy cooked millets tossed with finely cut crunchy vegetables and whole spices.',
        'inclusions' => "Millet Veg Pulav\nCucumber Raitha",
        'image_url' => 'assets/images/01 (13).jpeg',
        'display_order' => 5
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'lunch',
        'heading' => 'Millet Sadam',
        'subtitle' => 'Plain steamed wholesome millets, ideal replacement for white rice',
        'price' => 120.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'PURE MILLET',
        'description' => 'Nutrient-rich steamed whole grain millets to pair with any of our curries.',
        'inclusions' => "Steamed Organic Millet Sadam",
        'image_url' => 'assets/images/food_kerala_sadya.jpg',
        'display_order' => 6
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'breakfast',
        'heading' => 'Millet Puttu with Veg Curry',
        'subtitle' => 'Bamboo-steamed ragi and multi-millet puttu served with farm vegetable curry',
        'price' => 180.00,
        'price_note' => 'Per Set',
        'dietary_type' => 'veg',
        'badge' => 'WELLNESS COMBO',
        'description' => 'Nutritious layered steamed millet cylinder with grated coconut, served with a bowl of hot mixed veg curry.',
        'inclusions' => "Steamed Multi-Millet Puttu\nEarthen Pot Vegetable Curry",
        'image_url' => 'assets/images/01 (1).jpeg',
        'display_order' => 7
    ],
    [
        'category' => 'millet',
        'default_meal_time' => 'dinner',
        'heading' => 'Millet Kanji with Curry',
        'subtitle' => 'Warm, nourishing millet porridge cooked with crushed shallots, cumin & curry leaves',
        'price' => 140.00,
        'price_note' => 'Per Bowl Set',
        'dietary_type' => 'veg',
        'badge' => 'NIGHT COMFORT',
        'description' => 'Gentle comforting hot kanji simmered with medicinal hill herbs, accompanied by a flavorful side curry.',
        'inclusions' => "Steaming Millet Kanji Bowl\nSide Vegetable Curry\nRoasted Papadam & Pickle",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 8
    ],

    // --- CURRIES AND SIDES ---
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Nadan Chicken Curry',
        'subtitle' => 'Free-range country chicken braised in roasted coconut & cracked black pepper gravy',
        'price' => 1000.00,
        'price_note' => '₹1,000 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'VILLAGE COUNTRY CHICKEN',
        'description' => 'Authentic Kerala Nadan Kozhi Curry cooked in an earthen pot with toasted coconut, crushed garlic, and farm coriander.',
        'inclusions' => "Country Chicken in Rich Kerala Gravy (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 1
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Broiler Chicken Curry',
        'subtitle' => 'Tender broiler chicken simmered in spiced onion and tomato gravy',
        'price' => 800.00,
        'price_note' => '₹800 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'CHICKEN SPECIAL',
        'description' => 'Rich, flavorful chicken curry slow-cooked with fresh ginger, garlic, and ground spices.',
        'inclusions' => "Chicken Curry in Spiced Gravy (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 2
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Chicken Curry (Plate)',
        'subtitle' => 'Single dining plate portion of tender chicken curry in spiced Kerala gravy',
        'price' => 250.00,
        'price_note' => '₹250 / plate',
        'dietary_type' => 'non-veg',
        'badge' => 'PER PLATE',
        'description' => 'Portion of hot chicken curry, perfect companion for Kerala Rice, Porotta, or Chapathi.',
        'inclusions' => "1 Plate Chicken Curry",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 3
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Pepper Chicken',
        'subtitle' => 'Tender chicken tossed with freshly crushed high-altitude black pepper and curry leaves',
        'price' => 275.00,
        'price_note' => '₹275 / plate (₹1,100 / kg)',
        'dietary_type' => 'non-veg',
        'badge' => 'MARAYOOR PEPPER',
        'description' => 'Dry roasted chicken coated in pungent black pepper and shallots. Available per plate or per kg.',
        'inclusions' => "Spicy Pepper Roast Chicken",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Chilly Chicken',
        'subtitle' => 'Crisp fried chicken chunks tossed in spicy tangy chili garlic sauce with bell peppers',
        'price' => 275.00,
        'price_note' => '₹275 / plate (₹1,100 / kg)',
        'dietary_type' => 'non-veg',
        'badge' => 'INDO-CHINESE',
        'description' => 'Juicy chicken tossed with diced capsicum, onions, soy and fiery red chili glaze.',
        'inclusions' => "Chili Chicken Plate with Bell Peppers",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 5
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Chicken 65',
        'subtitle' => 'Crisp deep-fried spicy marinated chicken bites garnished with curry leaves & green chilies',
        'price' => 275.00,
        'price_note' => '₹275 / plate (₹1,100 / kg)',
        'dietary_type' => 'non-veg',
        'badge' => 'CRISPY APPETIZER',
        'description' => 'Golden fried boneless chicken bites marinated with fiery red chili, ginger-garlic paste, and crushed spices.',
        'inclusions' => "Hot Chicken 65 with Onion Rings & Lime",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 6
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Pallipalayam Chicken',
        'subtitle' => 'Rustic kongunadu style chicken braised with shallots, dry red chilies & coconut bits',
        'price' => 1100.00,
        'price_note' => '₹1,100 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'RUSTIC ROAST',
        'description' => 'Tender chicken pieces cooked dry without turmeric or coriander, flavored solely with shallots, dried red chilies, and crunchy coconut slivers.',
        'inclusions' => "Authentic Pallipalayam Chicken (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 7
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Dal Curry',
        'subtitle' => 'Yellow lentils tempered with ghee, cumin seeds, garlic, and fresh green chilies',
        'price' => 100.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'HOMELY COMFORT',
        'description' => 'Soothing comforting yellow dal slow-cooked to a creamy consistency, topped with ghee tadka.',
        'inclusions' => "Creamy Ghee Tempered Dal",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 8
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Chilly Gobi',
        'subtitle' => 'Crispy battered cauliflower florets tossed in sweet & spicy Indo-Chinese sauce',
        'price' => 200.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'CRISPY CAULIFLOWER',
        'description' => 'Crunchy cauliflower coated in light spiced batter, wok-tossed with capsicum, onions, and chili garlic sauce.',
        'inclusions' => "Crisp Chilly Gobi Plate",
        'image_url' => 'assets/images/01 (25).jpeg',
        'display_order' => 9
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Chilly Manjurian',
        'subtitle' => 'Deep fried vegetable dumplings tossed in ginger garlic Manchurian gravy',
        'price' => 150.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'MANCHURIAN',
        'description' => 'Soft vegetable fritters simmered in a tangy Indo-Chinese Manchurian glaze.',
        'inclusions' => "Veg Manchurian in Savory Sauce",
        'image_url' => 'assets/images/01 (25).jpeg',
        'display_order' => 10
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Veg Salad',
        'subtitle' => 'Crisp garden fresh cucumbers, tomatoes, carrots, and onions with lemon wedge',
        'price' => 100.00,
        'price_note' => 'Per Plate',
        'dietary_type' => 'veg',
        'badge' => 'FRESH CUT',
        'description' => 'Harvested crisp organic greens and garden vegetables sliced and chilled.',
        'inclusions' => "Platter of Fresh Cut Veggies & Lemon",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 11
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Fish Curry',
        'subtitle' => 'Fresh seasonal fish simmered in tangy kudampuli (pot tamarind) and coconut gravy',
        'price' => 250.00,
        'price_note' => 'As per size / catch',
        'dietary_type' => 'non-veg',
        'badge' => 'KOTTAYAM STYLE',
        'description' => 'Traditional claypot fish curry cooked with smoked kudampuli, fenugreek, shallots, and spicy chili gravy.',
        'inclusions' => "Claypot Fish Curry (Portion as per size)",
        'image_url' => 'assets/images/01 (30).jpeg',
        'display_order' => 12
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'lunch',
        'heading' => 'Fish Fry',
        'subtitle' => 'Tava fried fresh fish coated in spicy red chili, turmeric, and lime marinade',
        'price' => 250.00,
        'price_note' => 'As per size / catch',
        'dietary_type' => 'non-veg',
        'badge' => 'CRISPY TAVA ROAST',
        'description' => 'Fresh catch coated in Kerala masala and shallow-fried crisp on cast-iron tava in pure coconut oil.',
        'inclusions' => "Crispy Pan Fried Fish with Onion Rings",
        'image_url' => 'assets/images/01 (30).jpeg',
        'display_order' => 13
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Beef Fry',
        'subtitle' => 'Slow-roasted tender beef chunks tossed with coconut slivers & crushed pepper (Beef Ularthiyathu)',
        'price' => 1200.00,
        'price_note' => '₹1,200 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'ULARTHIYATHU ROAST',
        'description' => 'Iconic Kerala Beef Fry, pressure cooked and pan-roasted dark with freshly ground spices and roasted coconut slices.',
        'inclusions' => "Slow-Roast Spicy Beef Ularthiyathu (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 14
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Beef Curry',
        'subtitle' => 'Tender beef cubes slow-cooked in rich spiced onion-coriander gravy',
        'price' => 1000.00,
        'price_note' => '₹1,000 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'HOMESTYLE GRAVY',
        'description' => 'Succulent beef simmered slowly until melt-in-mouth tender in rich spiced gravy.',
        'inclusions' => "Spiced Beef Curry Gravy (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 15
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Mutton Fry',
        'subtitle' => 'Tender high-range mutton braised with crushed garlic, shallots & Kerala spices',
        'price' => 2100.00,
        'price_note' => '₹2,100 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'TENDER MUTTON',
        'description' => 'Succulent young mutton pan-roasted with native hill pepper and toasted coconut.',
        'inclusions' => "Spiced Mutton Fry (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 16
    ],
    [
        'category' => 'curries',
        'default_meal_time' => 'dinner',
        'heading' => 'Mutton Curry',
        'subtitle' => 'Juicy mutton simmered in rich Kashmiri chili and garam masala gravy',
        'price' => 1900.00,
        'price_note' => '₹1,900 / kg',
        'dietary_type' => 'non-veg',
        'badge' => 'RICH MUTTON GRAVY',
        'description' => 'Rich, deeply aromatic mutton curry slow cooked for hours to draw out all bone juices.',
        'inclusions' => "Rich Mutton Curry Gravy (Per Kg)",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 17
    ],

    // --- DINNER ---
    [
        'category' => 'dinner',
        'default_meal_time' => 'dinner',
        'heading' => 'Chapathi',
        'subtitle' => 'Soft whole wheat flatbread baked on iron tawa',
        'price' => 20.00,
        'price_note' => 'Per Piece',
        'dietary_type' => 'veg',
        'badge' => 'WHOLE WHEAT',
        'description' => 'Freshly rolled thin whole wheat chapathis puffed over live fire.',
        'inclusions' => "Soft Wheat Chapathi",
        'image_url' => 'assets/images/01 (31).jpeg',
        'display_order' => 1
    ],
    [
        'category' => 'dinner',
        'default_meal_time' => 'dinner',
        'heading' => 'Omelette / Bulls Eye',
        'subtitle' => 'Farm egg double omelette with shallots & pepper, or half-boiled bulls eye',
        'price' => 25.00,
        'price_note' => 'Per Order',
        'dietary_type' => 'non-veg',
        'badge' => 'FARM FRESH EGG',
        'description' => 'Made to order with fresh country eggs, black pepper, and curry leaves.',
        'inclusions' => "Hot Farm Egg Omelette or Bulls Eye",
        'image_url' => 'assets/images/01 (20).jpeg',
        'display_order' => 2
    ],
    [
        'category' => 'dinner',
        'default_meal_time' => 'dinner',
        'heading' => 'Paneer Butter Masala',
        'subtitle' => 'Soft cottage cheese cubes in rich buttery tomato & cashew cream gravy',
        'price' => 200.00,
        'price_note' => 'Per Portion',
        'dietary_type' => 'veg',
        'badge' => 'CREAMY DELIGHT',
        'description' => 'Tender paneer cubes simmered in velvety smooth, mildly spiced tomato cream sauce topped with farm butter.',
        'inclusions' => "Paneer Butter Masala Gravy",
        'image_url' => 'assets/images/01 (3).jpeg',
        'display_order' => 3
    ],
    [
        'category' => 'dinner',
        'default_meal_time' => 'dinner',
        'heading' => 'Bar-B-Que (Full)',
        'subtitle' => 'Whole chicken marinated in aromatic herbs & slow-grilled over teakwood charcoal embers',
        'price' => 820.00,
        'price_note' => 'Full Bird',
        'dietary_type' => 'non-veg',
        'badge' => 'WOODFIRE BBQ',
        'description' => 'Smoky, charred, succulent full chicken grilled over hot embers, served with garlic mayonnaise and mint relish.',
        'inclusions' => "Full Charcoal Grilled BBQ Chicken\nGarlic Dip & Mint Relish\nLime & Onion Salad",
        'image_url' => 'assets/images/01 (25).jpeg',
        'display_order' => 4
    ],
    [
        'category' => 'dinner',
        'default_meal_time' => 'dinner',
        'heading' => 'Bar-B-Que (Half)',
        'subtitle' => 'Half chicken marinated in herbs & roasted over aromatic charcoal embers',
        'price' => 440.00,
        'price_note' => 'Half Bird',
        'dietary_type' => 'non-veg',
        'badge' => 'WOODFIRE BBQ',
        'description' => 'Smoky tender half chicken grilled to perfection over fragrant charcoal.',
        'inclusions' => "Half Charcoal Grilled BBQ Chicken\nGarlic Dip & Relish",
        'image_url' => 'assets/images/01 (25).jpeg',
        'display_order' => 5
    ]
];

$ins = $pdo->prepare("INSERT INTO `food_menu` 
    (category, default_meal_time, heading, subtitle, price, price_note, description, inclusions, dietary_type, badge, image_url, gallery_images, display_order, is_active) 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)");

foreach ($menu_items as $item) {
    $gal = json_encode([$item['image_url']]);
    $ins->execute([
        $item['category'],
        $item['default_meal_time'],
        $item['heading'],
        $item['subtitle'],
        $item['price'],
        $item['price_note'],
        $item['description'],
        $item['inclusions'],
        $item['dietary_type'],
        $item['badge'],
        $item['image_url'],
        $gal,
        $item['display_order']
    ]);
}

// 3. Update Settings to match the printed menu card timings
$settings = [
    'menu_badge' => 'ESTATE GASTRONOMY & LIVING MENU',
    'menu_title' => 'Food Forest Farm Stay Heaven Menu',
    'menu_desc' => 'Every dish is prepared fresh on-site in traditional earthen pots and hearths. Outside food is strictly not allowed.',
    'menu_time_breakfast' => '09:00 AM — 10:00 AM',
    'menu_desc_breakfast' => 'Breakfast Service (09:00 AM – 10:00 AM) • Fresh Dosas, Idlis, Puttu, Kadala & Fresh Brews',
    'menu_time_lunch' => '12:30 PM — 02:30 PM',
    'menu_desc_lunch' => 'Lunch Service (12:30 PM – 02:30 PM) • Veg Meals, Biriyani, Fried Rice & Fresh Curries',
    'menu_time_snacks' => '04:30 PM — 06:30 PM',
    'menu_desc_snacks' => 'Evening Specials & Juices (04:30 PM – 06:30 PM) • Teas, Pazham Pori, Pakkavada & Pure Cane Juices',
    'menu_time_dinner' => '07:00 PM — 09:00 PM',
    'menu_desc_dinner' => 'Dinner Service (07:00 PM – 09:00 PM) • Chapathi, BBQ Chicken, Paneer Butter Masala & Curries'
];

$stmt_set = $pdo->prepare("REPLACE INTO `settings` (setting_key, setting_value) VALUES (?, ?)");
foreach ($settings as $k => $v) {
    $stmt_set->execute([$k, $v]);
}

$total_seeded = (int)$pdo->query("SELECT COUNT(*) FROM `food_menu`")->fetchColumn();
echo "Successfully seeded {$total_seeded} real dishes into `food_menu` table!\n";
